export const mockConversations = [
  {
    id: "1",
    name: "Martin Randolph",
    message: "Yes, 2pm is awesome",
    avatarUrl: "https://randomuser.me/api/portraits/men/10.jpg",
    seen: true,
    isImage: false,
    isAudio: false,
    isSentByUser: true,
  },
  {
    id: "2",
    name: "Karen Castillo",
    message: "",
    avatarUrl: "https://randomuser.me/api/portraits/women/20.jpg",
    seen: false,
    isImage: false,
    isAudio: true,
    duration: "0:14",
    isSentByUser: true,
  },
  {
    id: "3",
    name: "Martha Craig",
    message: "",
    avatarUrl: "https://randomuser.me/api/portraits/women/30.jpg",
    seen: false,
    isImage: true,
    isAudio: false,
    isSentByUser: false,
  },
  {
    id: "4",
    name: "Jacob Wood",
    message: "See you soon!",
    avatarUrl: "https://randomuser.me/api/portraits/men/40.jpg",
    seen: false,
    isImage: false,
    isAudio: false,
    isSentByUser: false,
  },
  {
    id: "5",
    name: "Linda Smith",
    message: "Got the files!",
    avatarUrl: "https://randomuser.me/api/portraits/women/50.jpg",
    seen: true,
    isImage: false,
    isAudio: false,
    isSentByUser: true,
  },
  {
    id: "6",
    name: "Daniel Murphy",
    message: "Check this out",
    avatarUrl: "https://randomuser.me/api/portraits/men/51.jpg",
    seen: false,
    isImage: true,
    isAudio: false,
    isSentByUser: true,
  },
  {
    id: "7",
    name: "Nina Taylor",
    message: "",
    avatarUrl: "https://randomuser.me/api/portraits/women/52.jpg",
    seen: false,
    isImage: false,
    isAudio: true,
    duration: "0:28",
    isSentByUser: false,
  },
  {
    id: "8",
    name: "Chris Evans",
    message: "Haha 😂",
    avatarUrl: "https://randomuser.me/api/portraits/men/53.jpg",
    seen: true,
    isImage: false,
    isAudio: false,
    isSentByUser: false,
  },
  {
    id: "9",
    name: "Samantha Rose",
    message: "Are we still on for today?",
    avatarUrl: "https://randomuser.me/api/portraits/women/54.jpg",
    seen: false,
    isImage: false,
    isAudio: false,
    isSentByUser: true,
  },
  {
    id: "10",
    name: "Brian Adams",
    message: "",
    avatarUrl: "https://randomuser.me/api/portraits/men/55.jpg",
    seen: false,
    isImage: true,
    isAudio: false,
    isSentByUser: false,
  },
  {
    id: "11",
    name: "Emily Clark",
    message: "Nice work!",
    avatarUrl: "https://randomuser.me/api/portraits/women/56.jpg",
    seen: true,
    isImage: false,
    isAudio: false,
    isSentByUser: true,
  },
  {
    id: "12",
    name: "Lucas Green",
    message: "",
    avatarUrl: "https://randomuser.me/api/portraits/men/57.jpg",
    seen: false,
    isImage: false,
    isAudio: true,
    duration: "0:07",
    isSentByUser: true,
  },
  {
    id: "13",
    name: "Jessica Lee",
    message: "On my way 🚗",
    avatarUrl: "https://randomuser.me/api/portraits/women/58.jpg",
    seen: false,
    isImage: false,
    isAudio: false,
    isSentByUser: false,
  },
  {
    id: "14",
    name: "Owen Hart",
    message: "",
    avatarUrl: "https://randomuser.me/api/portraits/men/59.jpg",
    seen: true,
    isImage: true,
    isAudio: false,
    isSentByUser: true,
  },
  {
    id: "15",
    name: "Hannah Moore",
    message: "",
    avatarUrl: "https://randomuser.me/api/portraits/women/60.jpg",
    seen: false,
    isImage: false,
    isAudio: true,
    duration: "0:12",
    isSentByUser: false,
  },
  {
    id: "16",
    name: "Ethan Reed",
    message: "No worries",
    avatarUrl: "https://randomuser.me/api/portraits/men/61.jpg",
    seen: true,
    isImage: false,
    isAudio: false,
    isSentByUser: false,
  },
  {
    id: "17",
    name: "Sophia Hill",
    message: "Let’s catch up soon",
    avatarUrl: "https://randomuser.me/api/portraits/women/62.jpg",
    seen: false,
    isImage: false,
    isAudio: false,
    isSentByUser: true,
  },
  {
    id: "18",
    name: "Isaac Turner",
    message: "",
    avatarUrl: "https://randomuser.me/api/portraits/men/63.jpg",
    seen: false,
    isImage: true,
    isAudio: false,
    isSentByUser: false,
  },
  {
    id: "19",
    name: "Grace Bennett",
    message: "",
    avatarUrl: "https://randomuser.me/api/portraits/women/64.jpg",
    seen: true,
    isImage: false,
    isAudio: true,
    duration: "0:21",
    isSentByUser: true,
  },
  {
    id: "20",
    name: "Leo Watson",
    message: "Talk later",
    avatarUrl: "https://randomuser.me/api/portraits/men/65.jpg",
    seen: false,
    isImage: false,
    isAudio: false,
    isSentByUser: true,
  },
];
