export const mockConversations = [
  {
    threadId: "1",
    members: ["user_123", "user_456"],
    lastMessage: { text: "Yes, 2pm is awesome", sender: "user_123" },
    photoURL: "https://randomuser.me/api/portraits/men/10.jpg",
    seen: true,
  },
  {
    threadId: "2",
    members: ["user_123", "user_457"],
    lastMessage: { text: "", sender: "user_123", isAudio: true, duration: "0:14" },
    photoURL: "https://randomuser.me/api/portraits/women/20.jpg",
    seen: false,
  },
  {
    threadId: "3",
    members: ["user_123", "user_458"],
    lastMessage: { text: "", sender: "user_458", isImage: true },
    photoURL: "https://randomuser.me/api/portraits/women/30.jpg",
    seen: false,
  },
  {
    threadId: "4",
    members: ["user_123", "user_459"],
    lastMessage: { text: "See you soon!", sender: "user_458" },
    photoURL: "https://randomuser.me/api/portraits/men/40.jpg",
    seen: false,
  },
  {
    threadId: "5",
    members: ["user_123", "user_460"],
    lastMessage: { text: "Got the files!", sender: "user_123" },
    photoURL: "https://randomuser.me/api/portraits/women/50.jpg",
    seen: true,
  },
  {
    threadId: "6",
    members: ["user_123", "user_461"],
    lastMessage: { text: "Check this out", sender: "user_123", isImage: true },
    photoURL: "https://randomuser.me/api/portraits/men/51.jpg",
    seen: false,
  },
  {
    threadId: "7",
    members: ["user_123", "user_462"],
    lastMessage: { text: "", sender: "user_462", isAudio: true, duration: "0:28" },
    photoURL: "https://randomuser.me/api/portraits/women/52.jpg",
    seen: false,
  },
  {
    threadId: "8",
    members: ["user_123", "user_463"],
    lastMessage: { text: "Haha 😂", sender: "user_462" },
    photoURL: "https://randomuser.me/api/portraits/men/53.jpg",
    seen: true,
  },
  {
    threadId: "9",
    members: ["user_123", "user_464"],
    lastMessage: { text: "Are we still on for today?", sender: "user_123" },
    photoURL: "https://randomuser.me/api/portraits/women/54.jpg",
    seen: false,
  },
  {
    threadId: "10",
    members: ["user_123", "user_465"],
    lastMessage: { text: "", sender: "user_465", isImage: true },
    photoURL: "https://randomuser.me/api/portraits/men/55.jpg",
    seen: false,
  },
  {
    threadId: "11",
    members: ["user_123", "user_466"],
    lastMessage: { text: "Nice work!", sender: "user_123" },
    photoURL: "https://randomuser.me/api/portraits/women/56.jpg",
    seen: true,
  },
  {
    threadId: "12",
    members: ["user_123", "user_467"],
    lastMessage: { text: "", sender: "user_123", isAudio: true, duration: "0:07" },
    photoURL: "https://randomuser.me/api/portraits/men/57.jpg",
    seen: false,
  },
  {
    threadId: "13",
    members: ["user_123", "user_468"],
    lastMessage: { text: "On my way 🚗", sender: "user_468" },
    photoURL: "https://randomuser.me/api/portraits/women/58.jpg",
    seen: false,
  },
  {
    threadId: "14",
    members: ["user_123", "user_469"],
    lastMessage: { text: "", sender: "user_123", isImage: true },
    photoURL: "https://randomuser.me/api/portraits/men/59.jpg",
    seen: true,
  },
  {
    threadId: "15",
    members: ["user_123", "user_470"],
    lastMessage: { text: "", sender: "user_470", isAudio: true, duration: "0:12" },
    photoURL: "https://randomuser.me/api/portraits/women/60.jpg",
    seen: false,
  },
  {
    threadId: "16",
    members: ["user_123", "user_471"],
    lastMessage: { text: "No worries", sender: "user_471" },
    photoURL: "https://randomuser.me/api/portraits/men/61.jpg",
    seen: true,
  },
  {
    threadId: "17",
    members: ["user_123", "user_472"],
    lastMessage: { text: "Let’s catch up soon", sender: "user_123" },
    photoURL: "https://randomuser.me/api/portraits/women/62.jpg",
    seen: false,
  },
  {
    threadId: "18",
    members: ["user_123", "user_473"],
    lastMessage: { text: "", sender: "user_473", isImage: true },
    photoURL: "https://randomuser.me/api/portraits/men/63.jpg",
    seen: false,
  },
  {
    threadId: "19",
    members: ["user_123", "user_474"],
    lastMessage: { text: "", sender: "user_123", isAudio: true, duration: "0:21" },
    photoURL: "https://randomuser.me/api/portraits/women/64.jpg",
    seen: true,
  },
  {
    threadId: "20",
    members: ["user_123", "user_475"],
    lastMessage: { text: "Talk later", sender: "user_123" },
    photoURL: "https://randomuser.me/api/portraits/men/65.jpg",
    seen: false,
  },
];
